"""empty message

Revision ID: 1f8202747267
Revises: 5f5e359109c8
Create Date: 2025-05-13 22:27:59.760843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8202747267'
down_revision = '5f5e359109c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_insight_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_panel_id', sa.Integer(), nullable=False),
    sa.Column('sharer_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('access_mode', sa.String(length=20), nullable=False),
    sa.Column('shared_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['original_panel_id'], ['insight_panel.id'], name='fk_shared_original_panel_id'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='fk_shared_recipient_id'),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.id'], name='fk_shared_sharer_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_panel_id', 'recipient_id', name='_original_panel_recipient_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_insight_panel')
    # ### end Alembic commands ###
