"""empty message

Revision ID: 2666b9e13a1e
Revises: 2b93a3baa807
Create Date: 2025-05-09 16:45:53.243897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2666b9e13a1e'
down_revision = '2b93a3baa807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=False))
        batch_op.drop_column('location_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_key', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
