"""empty message

Revision ID: 2b93a3baa807
Revises: dd8c5cb07b4b
Create Date: 2025-05-09 16:35:52.466188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b93a3baa807'
down_revision = 'dd8c5cb07b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_key', sa.String(length=120), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('location_key')

    # ### end Alembic commands ###
