"""empty message

Revision ID: 361607381e69
Revises: 92aa422d54d5
Create Date: 2025-05-11 13:40:01.870745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361607381e69'
down_revision = '92aa422d54d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_member_edit_name', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allow_member_edit_description', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allow_member_manage_members', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('allow_member_manage_members')
        batch_op.drop_column('allow_member_edit_description')
        batch_op.drop_column('allow_member_edit_name')

    # ### end Alembic commands ###
