"""empty message

Revision ID: 4d27a5cbf23f
Revises: 03618a0bda36
Create Date: 2025-05-01 13:04:31.981020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d27a5cbf23f'
down_revision = '03618a0bda36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_rsvp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('rsvp_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsvp_status', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('event_rsvp', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
