"""new fields in user model

Revision ID: 71099a91c499
Revises: 24164de95a87
Create Date: 2025-04-22 14:22:44.570784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71099a91c499'
down_revision = '24164de95a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
