"""empty message

Revision ID: 819278932e33
Revises: 2e2f49f56a26
Create Date: 2025-04-26 14:48:04.627053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819278932e33'
down_revision = '2e2f49f56a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('y')
        batch_op.drop_column('x')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
