"""empty message

Revision ID: a84f55c391c5
Revises: 4d27a5cbf23f
Create Date: 2025-05-07 22:25:13.520231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84f55c391c5'
down_revision = '4d27a5cbf23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('event_rsvp', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_event_uc', ['user_id', 'event_id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)

    with op.batch_alter_table('event_rsvp', schema=None) as batch_op:
        batch_op.drop_constraint('_user_event_uc', type_='unique')

    op.drop_table('friends')
    # ### end Alembic commands ###
