"""empty message

Revision ID: f655319e9e4c
Revises: 9ca5045f207d
Create Date: 2025-04-23 13:48:39.487560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f655319e9e4c'
down_revision = '9ca5045f207d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('x',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('x',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('about')

    # ### end Alembic commands ###
